### ISSUE TITLE
Error when running server

### ISSUE THREAD

**Issue by GSManganneau** [A11yWatch/node-iframe#5] opened 2021-01-04 15:18 UTC
Hello :)
Thank you for your work on this project.
I was looking for a way to do serverside-rendering for iframe and google lead me here.

There is the code I am trying to run

```
const express = require('express')
const createIframe = require("node-iframe")
const app = express();
const PORT = 8000;

app.use(createIframe)

app.get("/group1/dashboard_name_1", (req, res) => {
    res.createIframe({
      url: "http://dashboard_name_1:8501"
    })
  })
  
  app.get("/group1/dashboard_name_2", (req, res) => {
    res.createIframe({
      url: "http://dashboard_name_1:8502"
    })
  })

app.listen(PORT, () => {
  console.log(`⚡️[server]: Server is running at https://localhost:${PORT}`);
```

I got this error:

```
/node_modules/express/lib/application.js:210
    throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (node_modules/express/lib/application.js:210:11)
    at Object.<anonymous> (server.js:8:5)
```

any idea how to solve it ?

Thank you for your time if you reading this :)

**Comment by j-mendez** [comment] 2021-01-04 20:24
> Hello :)
> Thank you for your work on this project.
> I was looking for a way to do serverside-rendering for iframe and google lead me here.
> 
> There is the code I am trying to run
> 
> ```
> const express = require('express')
> const createIframe = require("node-iframe")
> const app = express();
> const PORT = 8000;
> 
> app.use(createIframe)
> 
> app.get("/group1/dashboard_name_1", (req, res) => {
>     res.createIframe({
>       url: "http://dashboard_name_1:8501"
>     })
>   })
>   
>   app.get("/group1/dashboard_name_2", (req, res) => {
>     res.createIframe({
>       url: "http://dashboard_name_1:8502"
>     })
>   })
> 
> app.listen(PORT, () => {
>   console.log(`⚡️[server]: Server is running at https://localhost:${PORT}`);
> ```
> 
> I got this error:
> 
> ```
> /node_modules/express/lib/application.js:210
>     throw new TypeError('app.use() requires a middleware function')
>     ^
> 
> TypeError: app.use() requires a middleware function
>     at Function.use (node_modules/express/lib/application.js:210:11)
>     at Object.<anonymous> (server.js:8:5)
> ```
> 
> any idea how to solve it ?
> 
> Thank you for your time if you reading this :)

@GSManganneau your welcome, what version of the package are you using?

**Comment by j-mendez** [comment] 2021-01-05 01:10
@GSManganneau your welcome, what version of node are you running?

**Comment by j-mendez** [comment] 2021-01-30 14:55
Going to close this down, since I am having trouble reproducing this.

**Closed as completed by j-mendez** 2021-01-30 14:55 UTC
